version: '3'
services:
  doccano:
    container_name: doccano-web
    build: ./
    ports:
      - 1664:1664
    volumes:
      - ./:/doccano_data
    restart: on-failure
    tty: true
    stdin_open: true